version: "3.7"

services:
  client_db:
    container_name: client_db
    image: postgres:14.0
    ports:
      - "5400:5432"
    restart: always
    environment:
      POSTGRES_DB: client
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
