--liquibase formatted sql

--changeset Ilya:1
--comment create client_types table
CREATE TABLE client_types
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_name       VARCHAR(60)                             NOT NULL,
    full_name        VARCHAR(255)                            NOT NULL,
    client_type_code VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_client_types PRIMARY KEY (id)
);

INSERT INTO client_types(short_name, full_name, client_type_code) VALUES ('B2C', 'Потребители', 'b2c');
INSERT INTO client_types(short_name, full_name, client_type_code) VALUES ('B2B', 'Оптовые покупатели', 'b2b');
INSERT INTO client_types(short_name, full_name, client_type_code) VALUES ('B2G', 'Государственные организации', 'b2g');
--rollback truncate table client_types;


--changeset Ilya:2
--comment create client table
CREATE TABLE client
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_name        VARCHAR(60)                             NOT NULL,
    full_name         VARCHAR(255)                            NOT NULL,
    client_type       BIGINT                                  NOT NULL,
    inn               VARCHAR(12)                             NOT NULL,
    okpo              VARCHAR(10),
    creation_data     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modification_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_CLIENT_TYPES FOREIGN KEY (client_type) REFERENCES client_types (id);

INSERT INTO client (short_name, full_name, client_type, inn, okpo, creation_data, modification_date)
values ('ООО Компания #1', 'Общество с ограниченной отвественностью Компания #1', 1, 111111111111, 1111111111, now(), now());

INSERT INTO client (short_name, full_name, client_type, inn, okpo, creation_data, modification_date)
values ('ООО Компания #2', 'Общество с ограниченной отвественностью Компания #2', 2, 222222222222, 2222222222, now(), now());

INSERT INTO client (short_name, full_name, client_type, inn, okpo, creation_data, modification_date)
values ('ООО Компания #3', 'Общество с ограниченной отвественностью Компания #3', 3, 333333333333, 3333333333, now(), now());

INSERT INTO client (short_name, full_name, client_type, inn, okpo, creation_data, modification_date)
values ('ООО Компания #4', 'Общество с ограниченной отвественностью Компания #4', 1, 444444444444, 4444444444, now(), now());

INSERT INTO client (short_name, full_name, client_type, inn, okpo, creation_data, modification_date)
values ('ООО Компания #5', 'Общество с ограниченной отвественностью Компания #5', 2, 555555555555, 5555555555, now(), now());

INSERT INTO client (short_name, full_name, client_type, inn, okpo, creation_data, modification_date)
values ('ООО Компания #6', 'Общество с ограниченной отвественностью Компания #6', 3, 666666666666, 6666666666, now(), now());
--rollback truncate table client;